# Generated by Django 3.1.7 on 2022-11-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priklad',
            options={'verbose_name': 'Příklad', 'verbose_name_plural': 'Příklady'},
        ),
    ]
