# Generated by Django 3.1.7 on 2022-11-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0003_reseni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucebnice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Učebnice',
                'verbose_name_plural': 'Učebnice',
            },
        ),
        migrations.AddField(
            model_name='reseni',
            name='je_spravne',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='reseni',
            name='FK_priklad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='math_app.priklad'),
        ),
        migrations.CreateModel(
            name='Kapitola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('FK_ucebnice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='math_app.ucebnice')),
            ],
            options={
                'verbose_name': 'Kapitola',
                'verbose_name_plural': 'Kapitoly',
            },
        ),
        migrations.CreateModel(
            name='Cviceni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('FK_kapitola', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='math_app.kapitola')),
            ],
            options={
                'verbose_name': 'Cvičení',
                'verbose_name_plural': 'Cvičení',
            },
        ),
        migrations.AddField(
            model_name='priklad',
            name='FK_cviceni',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='math_app.cviceni'),
        ),
    ]
