# Generated by Django 4.1.3 on 2022-11-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0007_alter_ucebnice_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ucebnice',
            name='author',
        ),
    ]
