# Generated by Django 4.1.3 on 2022-11-23 10:22

from django.db import migrations, models
import math_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0008_remove_ucebnice_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucebnice',
            name='obrazek',
            field=models.ImageField(default=None, null=True, upload_to=math_app.models.get_image_ucebnice),
        ),
    ]
