# Generated by Django 4.1.3 on 2022-11-24 18:48

from django.db import migrations, models
import math_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0011_alter_ucebnice_obrazek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cviceni',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kapitola',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='priklad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reseni',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ucebnice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ucebnice',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to=math_app.models.get_image_ucebnice),
        ),
    ]
