# Generated by Django 4.1.3 on 2022-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0012_alter_cviceni_id_alter_kapitola_id_alter_priklad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucebnice',
            name='autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ucebnice',
            name='cas_vytvoreni',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ucebnice',
            name='cas_zmeny',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
