# Generated by Django 4.1.3 on 2022-11-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0015_alter_kapitola_fk_ucebnice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseni',
            name='cas',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
