# Generated by Django 4.1.3 on 2022-12-20 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_app', '0017_reseni_uzivatel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseni',
            name='uzivatel',
        ),
        migrations.AddField(
            model_name='reseni',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
