# Generated by Django 4.1.3 on 2023-01-04 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('math_app', '0018_remove_reseni_uzivatel_reseni_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucebnice',
            name='muze_pocitat',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
