# Generated by Django 4.1.3 on 2023-01-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0019_ucebnice_muze_pocitat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucebnice',
            old_name='muze_pocitat',
            new_name='muzou_pocitat',
        ),
    ]
