# Generated by Django 4.1.3 on 2023-01-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_app', '0020_rename_muze_pocitat_ucebnice_muzou_pocitat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucebnice',
            old_name='muzou_pocitat',
            new_name='muzou_editovat',
        ),
    ]
